language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 --max-line-length=88
  - black --check .

script:
  - coverage run --source=mysite,polls manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml

branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA33LUXQZVZ6RASJ4M"
  secret_access_key: "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"
  region: "us-east-2"
  app: "polls"
  env: "Polls-env"
  bucket_name: "elasticbeanstalk-us-east-2-814677984875"

  on:
    branch: main