language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 --max-line-length=88
  - black --check .

script:
  - coverage run --source=mysite,polls manage.py test
  - coverage xml
  - COVERALLS_REPO_TOKEN=Hsuqw6orXndIyhXF8sAwVlPSTz3YD9TRn coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "polls"
  env: "Polls-env"
  bucket_name: "elasticbeanstalk-us-east-2-814677984875"

  on:
    branch: main