language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 --max-line-length=88
  - black --check .

script:
  - coverage run --source=mysite,polls manage.py test
  - coverage xml
  - COVERALLS_REPO_TOKEN=Hsuqw6orXndIyhXF8sAwVlPSTz3YD9TRn coveralls


branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIA33LUXQZVXAGHLZTF"
  secret_access_key: "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"
  region: "us-east-2"
  app: "polls"
  env: "Polls-env"
  bucket_name: "elasticbeanstalk-us-east-2-814677984875"

